"use client";

import { useEffect, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/Feedback";
import { inputClass, labelClass } from "@/components/FormControls";
import { Shell } from "@/components/Shell";
import { TaskCard } from "@/components/TaskCard";
import { getProjects, getTags, Project, searchTasks, Tag, WorkTask } from "@/lib/api";

export default function SearchPage() {
  const [filters, setFilters] = useState({ title: "", status: "", priority: "", projectId: "", tagId: "" }); const [projects, setProjects] = useState<Project[]>([]); const [tags, setTags] = useState<Tag[]>([]); const [items, setItems] = useState<WorkTask[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getProjects(), getTags()]).then(([p, t]) => { setProjects(p); setTags(t); }).catch((e) => setError(e.message)); }, []);
  useEffect(() => { const timer = setTimeout(() => { setLoading(true); const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value) params.set(key, value); }); searchTasks(params.toString()).then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, 250); return () => clearTimeout(timer); }, [filters]);
  const change = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));
  return <Shell><p className="text-sm font-semibold uppercase tracking-widest text-indigo-600">Discovery</p><h1 className="mt-2 text-3xl font-black">Search tasks</h1><div className="mt-7 grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-2 lg:grid-cols-5"><label className={labelClass}>Title<input className={inputClass} value={filters.title} onChange={(e) => change("title", e.target.value)} placeholder="Search title" /></label><label className={labelClass}>Status<select className={inputClass} value={filters.status} onChange={(e) => change("status", e.target.value)}><option value="">All statuses</option><option value="0">To Do</option><option value="1">In Progress</option><option value="2">Done</option><option value="3">Cancelled</option></select></label><label className={labelClass}>Priority<select className={inputClass} value={filters.priority} onChange={(e) => change("priority", e.target.value)}><option value="">All priorities</option><option value="0">Low</option><option value="1">Medium</option><option value="2">High</option><option value="3">Critical</option></select></label><label className={labelClass}>Project<select className={inputClass} value={filters.projectId} onChange={(e) => change("projectId", e.target.value)}><option value="">All projects</option>{projects.map((p) => <option key={p.projectId} value={p.projectId}>{p.projectName}</option>)}</select></label><label className={labelClass}>Tag<select className={inputClass} value={filters.tagId} onChange={(e) => change("tagId", e.target.value)}><option value="">All tags</option>{tags.map((tag) => <option key={tag.tagId} value={tag.tagId}>{tag.tagName}</option>)}</select></label></div><div className="mb-4 mt-8 flex items-center justify-between"><h2 className="text-xl font-black">Results</h2><span className="text-sm text-slate-500">{items.length} tasks</span></div>{error ? <ErrorState message={error} /> : loading ? <LoadingState label="Searching tasks..." /> : items.length === 0 ? <EmptyState message="No tasks match these filters." /> : <div className="grid gap-4 md:grid-cols-2">{items.map((task) => <TaskCard key={task.taskId} task={task} />)}</div>}</Shell>;
}
