"use client";

import { FormEvent, useEffect, useState } from "react";
import { ConfirmDialog, Modal } from "@/components/Dialogs";
import { ErrorState, LoadingState, Toast } from "@/components/Feedback";
import { dangerButton, editButton, inputClass, labelClass, primaryButton, secondaryButton } from "@/components/FormControls";
import { ManagementNav } from "@/components/ManagementNav";
import { Shell } from "@/components/Shell";
import { createDepartment, deleteDepartment, Department, getDepartments, updateDepartment } from "@/lib/api";

const emptyForm = { departmentName: "", departmentDescription: "" };
export default function DepartmentManagementPage() {
  const [items, setItems] = useState<Department[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Department | null>(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<Department | null>(null); const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const load = () => { setLoading(true); getDepartments().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { getDepartments().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setModal(true); };
  const openEdit = (item: Department) => { setEditing(item); setForm({ departmentName: item.departmentName, departmentDescription: item.departmentDescription }); setModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.departmentName.trim() || !form.departmentDescription.trim()) return setToast({ message: "Name and description are required.", type: "error" }); setSaving(true); try { if (editing) await updateDepartment(editing.departmentId, form); else await createDepartment(form); setModal(false); setToast({ message: `Department ${editing ? "updated" : "created"}.`, type: "success" }); load(); } catch (e) { setToast({ message: (e as Error).message, type: "error" }); } finally { setSaving(false); } };
  const confirmDelete = async () => { if (!deleting) return; try { await deleteDepartment(deleting.departmentId); setToast({ message: "Department deleted.", type: "success" }); setDeleting(null); load(); } catch (e) { setToast({ message: (e as Error).message, type: "error" }); setDeleting(null); } };
  return <Shell>{toast && <Toast {...toast} onClose={() => setToast(null)} />}<ManagementNav /><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black">Department management</h1><p className="mt-1 text-slate-500">Create, edit, and delete departments.</p></div><button onClick={openCreate} className={primaryButton}>+ New department</button></div>{error ? <div className="mt-6"><ErrorState message={error} /></div> : loading ? <LoadingState /> : <div className="mt-7 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Department</th><th className="px-5 py-4">Description</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.departmentId}><td className="px-5 py-4 font-bold">{item.departmentName}</td><td className="max-w-xl px-5 py-4 text-slate-500">{item.departmentDescription}</td><td className="whitespace-nowrap px-5 py-4 text-right"><button onClick={() => openEdit(item)} className={editButton}>Edit</button><button onClick={() => setDeleting(item)} className={dangerButton}>Delete</button></td></tr>)}</tbody></table></div>}<Modal open={modal} title={editing ? "Edit department" : "Create department"} onClose={() => setModal(false)}><form onSubmit={submit} className="space-y-5"><label className={labelClass}>Department name<input className={inputClass} maxLength={100} required value={form.departmentName} onChange={(e) => setForm({ ...form, departmentName: e.target.value })} /></label><label className={labelClass}>Description<textarea className={`${inputClass} min-h-28`} maxLength={300} required value={form.departmentDescription} onChange={(e) => setForm({ ...form, departmentDescription: e.target.value })} /></label><div className="flex justify-end gap-3"><button type="button" onClick={() => setModal(false)} className={secondaryButton}>Cancel</button><button disabled={saving} className={primaryButton}>{saving ? "Saving..." : "Save"}</button></div></form></Modal><ConfirmDialog open={!!deleting} title="Delete department?" message="The department can only be deleted when no projects are linked to it." onCancel={() => setDeleting(null)} onConfirm={confirmDelete} /></Shell>;
}
