"use client";

import { FormEvent, useEffect, useState } from "react";
import { ConfirmDialog, Modal } from "@/components/Dialogs";
import { ErrorState, LoadingState, Toast } from "@/components/Feedback";
import { dangerButton, editButton, inputClass, labelClass, primaryButton, secondaryButton } from "@/components/FormControls";
import { ManagementNav } from "@/components/ManagementNav";
import { Shell } from "@/components/Shell";
import { createTag, deleteTag, getTags, Tag, updateTag } from "@/lib/api";

const emptyForm = { tagName: "", color: "#6366F1" };
export default function TagManagementPage() {
  const [items, setItems] = useState<Tag[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [modal, setModal] = useState(false); const [editing, setEditing] = useState<Tag | null>(null); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [deleting, setDeleting] = useState<Tag | null>(null); const [toast, setToast] = useState<{ message: string; type: "success" | "error" } | null>(null);
  const load = () => { setLoading(true); getTags().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); }; useEffect(() => { getTags().then(setItems).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setModal(true); }; const openEdit = (item: Tag) => { setEditing(item); setForm({ tagName: item.tagName, color: item.color || "#6366F1" }); setModal(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.tagName.trim()) return; setSaving(true); try { if (editing) await updateTag(editing.tagId, form); else await createTag(form); setModal(false); setToast({ message: `Tag ${editing ? "updated" : "created"}.`, type: "success" }); load(); } catch (e) { setToast({ message: (e as Error).message, type: "error" }); } finally { setSaving(false); } };
  const confirmDelete = async () => { if (!deleting) return; try { await deleteTag(deleting.tagId); setToast({ message: "Tag deleted.", type: "success" }); setDeleting(null); load(); } catch (e) { setToast({ message: (e as Error).message, type: "error" }); setDeleting(null); } };
  return <Shell>{toast && <Toast {...toast} onClose={() => setToast(null)} />}<ManagementNav /><div className="flex items-center justify-between"><div><h1 className="text-3xl font-black">Tag management</h1><p className="mt-1 text-slate-500">Maintain task labels and colors.</p></div><button onClick={openCreate} className={primaryButton}>+ New tag</button></div>{error ? <div className="mt-6"><ErrorState message={error} /></div> : loading ? <LoadingState /> : <div className="mt-7 overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Tag</th><th className="px-5 py-4">Color</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.tagId}><td className="px-5 py-4"><span className="rounded-full px-3 py-1 text-xs font-bold" style={{ backgroundColor: `${item.color || "#64748b"}22`, color: item.color || "#475569" }}>{item.tagName}</span></td><td className="px-5 py-4 text-slate-500"><span className="mr-2 inline-block h-4 w-4 rounded-full align-middle" style={{ backgroundColor: item.color }} />{item.color || "None"}</td><td className="whitespace-nowrap px-5 py-4 text-right"><button onClick={() => openEdit(item)} className={editButton}>Edit</button><button onClick={() => setDeleting(item)} className={dangerButton}>Delete</button></td></tr>)}</tbody></table></div>}<Modal open={modal} title={editing ? "Edit tag" : "Create tag"} onClose={() => setModal(false)}><form onSubmit={submit} className="space-y-5"><label className={labelClass}>Tag name<input className={inputClass} maxLength={50} required value={form.tagName} onChange={(e) => setForm({ ...form, tagName: e.target.value })} /></label><label className={labelClass}>Color<div className="mt-1 flex gap-3"><input type="color" className="h-11 w-16 rounded-lg border p-1" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value.toUpperCase() })} /><input className={inputClass.replace("mt-1 ", "")} pattern="^#[0-9A-Fa-f]{6}$" required value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></div></label><div className="flex justify-end gap-3"><button type="button" onClick={() => setModal(false)} className={secondaryButton}>Cancel</button><button disabled={saving} className={primaryButton}>{saving ? "Saving..." : "Save"}</button></div></form></Modal><ConfirmDialog open={!!deleting} title="Delete tag?" message="A tag can only be deleted when it is not used by any task." onCancel={() => setDeleting(null)} onConfirm={confirmDelete} /></Shell>;
}
